stages:
  - build
  - release

workflow:
  rules:
    - if: $CI_COMMIT_TAG

variables:
  TEMP_DIR: 'C:\buildTemp'
  WORKING_DIR: '$TEMP_DIR\App'
  BUILD_OUTPUT: '$WORKING_DIR\dist'
  FINAL_BUILD_DIR: 'C:\builds\project\app\dist'  # Replace with actual location or make it an env var

build_app:
  stage: build
  tags:
    - windows
  script:
    - powershell -Command "
        if (Test-Path '$env:TEMP_DIR') { Remove-Item -Recurse -Force '$env:TEMP_DIR' };
        robocopy . '$env:TEMP_DIR' /MIR;
        Set-Location '$env:WORKING_DIR';
        npm install;
        npm run dist;
        exit $LASTEXITCODE
      "
    - powershell -Command "
        robocopy '$env:BUILD_OUTPUT' '$env:FINAL_BUILD_DIR' /MIR;
        exit $LASTEXITCODE
      "
  artifacts:
    paths:
      - App/dist
  cache:
    key: ${CI_COMMIT_REF_SLUG}
    paths:
      - App/node_modules/

release:
  stage: release
  tags:
    - windows
  before_script:
    - dir
    - dir App\dist
  script:
    - $exeFile = Get-ChildItem -Path "App\dist" -Filter *.exe | Select-Object -First 1
    - $ymlFile = Get-ChildItem -Path "App\dist" -Filter latest.yml | Select-Object -First 1
    - $encodedName = [uri]::EscapeDataString($exeFile.Name)
    - |
      Invoke-RestMethod -Method Post -Uri "https://gitlab.com/api/v4/projects/$env:CI_PROJECT_ID/releases" `
        -Headers @{ "PRIVATE-TOKEN" = "$env:GITLAB_TOKEN" } `
        -Body @{
            name = "Release $env:CI_COMMIT_TAG"
            tag_name = "$env:CI_COMMIT_TAG"
            ref = "$env:CI_COMMIT_TAG"
            description = "Automated release from pipeline"
        }
    - |
      Invoke-RestMethod -Method Put `
        -Uri "https://gitlab.com/api/v4/projects/$env:CI_PROJECT_ID/packages/generic/my-app/$env:CI_COMMIT_TAG/$encodedName" `
        -Headers @{ "PRIVATE-TOKEN" = "$env:GITLAB_TOKEN" } `
        -InFile $exeFile.FullName
    - |
      if ($ymlFile) {
        Invoke-RestMethod -Method Put `
          -Uri "https://gitlab.com/api/v4/projects/$env:CI_PROJECT_ID/packages/generic/my-app/$env:CI_COMMIT_TAG/latest.yml" `
          -Headers @{ "PRIVATE-TOKEN" = "$env:GITLAB_TOKEN" } `
          -InFile $ymlFile.FullName
      }
  dependencies:
    - build_app